### ISSUE TITLE
v2.4 does not detect duplicates well

### ISSUE THREAD

**Issue by ignacioserna** [elisemercury/Duplicate-Image-Finder#25]
Hi @elisemercury, thank you for your work.

I am seeing that with version 2.4 something has changed so that the duplicate detection no longer works properly. I don't know what it could be.
The output format hasn't changed, has it? Is it necessary to adapt our code to the new version?

**Comment by elisemercury** [comment]
Hi @ignacioserna!

Thanks a lot for noticing and opening the issue! The issue should now be fixed with **version v2.4.1**. In case the issue should sill persist, please feel free to let me know and post any details around your scenario i. e. which difPy parameters are you using, how many files are you searching through, and the error message you are getting. Again, thanks a lot!

All the best,
Elise
