### ISSUE TITLE
Near duplicate Image detection

### ISSUE THREAD

**Issue by dhruvbhatnagar9548** [elisemercury/Duplicate-Image-Finder#29]
Hello, first of all thanks for creating this package It is really good package for detecting Duplicate images.
I have tried this package I have found that it is able to detect images which are 100% similarity but I have found that it was not able to detect the images when similarity is not 100% even if similarity is 99.99% or less not able to detect image. 
I have tried to play with the pixel values and similarity but than also it was not able to detect. So, is there ways to detect such image which having similarity score less than 100% by using difpy package.

I have attached few images which it was not able to detect.
Note:- The percentage values which I have refereed many times found from matchTemplate method the images which are attached having similarity is 99%.

![TOI_Delhi_12-07-2022_4_1](https://user-images.githubusercontent.com/86790520/178800667-f2aa8728-d8ec-4b77-a00e-b6f2e7780705.jpg)
![TOI_Delhi_12-07-2022_4_2](https://user-images.githubusercontent.com/86790520/178800676-8c7c6b88-5541-4aa7-b92d-097f329cc1c7.jpg)
![TOI_Delhi_12-07-2022_4_3](https://user-images.githubusercontent.com/86790520/178800687-3f3118f0-b2b1-407a-8c51-bf25d7d0e29a.jpg)
![TOI_Delhi_12-07-2022_4_7](https://user-images.githubusercontent.com/86790520/178800699-cb7c3f8a-856e-4bed-b367-9582f229d2c5.jpg)
![TOI_Delhi_12-07-2022_4_8](https://user-images.githubusercontent.com/86790520/178800708-115d2756-4cee-4d8b-9e30-92bc4dcd9db7.jpg)

**Comment by elisemercury** [comment]
Hi @dhruvbhatnagar9548,
Thanks a lot for opening the issue and for the feedback! 
I just tested difPy on your images, and indeed it does not recognize them as duplicates. This is because of to the difference in tensors that the images have: due to the frame on some images, and the crop difference. DifPy computes the following MSE values for your images ("weareone" = a, "bus" = b):
- a1 and a2 = 7298
- a1 and a3 = 13218
- b1 and b2 = 9774

DifPy only considers images as being similar if they have an MSE of less than 1000 (with the `similarity` parameter `='low'`). Therefore, in order to solve your issue, you would need to adjust the MSE threshold. You can do this yourself by forking the difPy code and adjusting it, or wait until the next difPy release which will include an option to set the MSE threshold value directly from the `similarity` parameter.

I hope this helps!

Again, thanks a lot and all the best,
Elise

**Comment by dhruvbhatnagar9548** [comment]
Thanks for the reply. I will try the solution that you have mentioned. Thanks.
