### ISSUE TITLE
Misspelled variable

### ISSUE THREAD

**Issue by builder35** [elisemercury/Duplicate-Image-Finder#59]
https://github.com/elisemercury/Duplicate-Image-Finder/blob/main/difPy/dif.py#L63
exlude_from_search should be exclude_from_search

Though it doesn't seemed to be getting used right now. But my guess is you may want to use it in future iterations

**Comment by elisemercury** [comment]
Hi @builder35,

Thanks a lot for noticing! Indeed, this was a typo. As of v3.0.1, this variable is not reused anywhere in the code. It is set as placeholder, in case there is a need for it in the future, like you guessed. Therefore, it will not infer with any of the difPy processes and no exception will be thrown. Nevertheless, even if it is not used, the typo will definitely be fixed in the next release.

Again thanks and all the best,
Elise
