### ISSUE TITLE
Similar or Duplicate images aren't recognized at all

### ISSUE THREAD

**Issue by bayoleems** [elisemercury/Duplicate-Image-Finder#62]

**Comment by elisemercury** [comment]
Hi @bayoleems 

Can you please provide a bit more detail to your issue? With no information, we cannot relate to the issue you are having.

Thank you and best,
Elise

**Comment by bayoleems** [comment]
Hi @elisemercury 
![image](https://user-images.githubusercontent.com/108756247/220183575-67a234b0-2514-4194-a7b9-9ee1920a7892.jpeg)

I have a couple of similar and duplicate images in the directory put the package keeps returning 0 values.

**Comment by bayoleems** [comment]
Hi @elisemercury 
I've got similar and duplicate images in the directory but the package keeps returning 0 values for duplicate/similar Images
![image](https://user-images.githubusercontent.com/108756247/220184225-081815cf-7df9-46aa-9103-e25658acd72e.jpeg)

**Comment by elisemercury** [comment]
Hi @bayoleems,

Thanks for clarifying! I'll be happy to try and find the issue you are running into - for that, could you please answer the following questions for me?

* Which version of difPy are you running?
* Which file types are the images you are comparing?
* Could you please provide me with the output of `search.stats`?
* If you would like difPy algorithm to find similar images, I recommend to set `similarity` to `'low'`. Could you please try this and check the output? When similarity is set to `'normal'` it will search for duplicate images.
* Any specific reason you are using `px_size=10` instead of the default value `50`?

Thank you and all the best,
Elise

**Comment by bayoleems** [comment]
Hi @elisemercury 

I'm using the recent version from the repo and comparing .jpg image files. 

![image](https://user-images.githubusercontent.com/108756247/220337179-3521e37a-23c6-4323-a1c1-3f88dcd76c5d.jpeg)

from the search.stats json there's a number of invalid files which I think might be a reason for the issue. What does it mean by invalid file? 

Lastly I used px value as 10 cause I thought it would be more precise in similarity matching 

![image](https://user-images.githubusercontent.com/108756247/220338127-04cd9f64-b1bb-48a6-bd06-193752f0017e.jpeg)

I still get the same thing even after changing the similarity to low and px to 50.

Thank you.
