### ISSUE TITLE
Make the package installable and usable via `pipx`

### ISSUE THREAD

**Issue by yujinyuz** [elisemercury/Duplicate-Image-Finder#71]
Thanks for this package! Currently using this right now to cleanup my hard drive.

Packages like `flake8`, `pytest`, `ruff` can be run in the cli just by typing their package name.

I noticed that this package does not do that and you have to `cd` into the directory where you installed this based on this issue: https://github.com/elisemercury/Duplicate-Image-Finder/issues/49

Try running `pipx install ruff` and it automatically creates a virtualenv and adds `ruff` to the $PATH and you can use it anywhere.

---

I think it would be great to have this package support it.

This is the output when I run `pipx install difPy`

```console
pipx install difPy
Note: Dependent package 'numpy' contains 3 apps
  - f2py
  - f2py3
  - f2py3.11
Note: Dependent package 'fonttools' contains 4 apps
  - fonttools
  - pyftmerge
  - pyftsubset
  - ttx
```

**Comment by elisemercury** [comment]
Hi @yujinyuz,

Thanks for the feature suggestion! Indeed I agree this is a very handy feature. It will be implemented as part of the next difPy version which will be released shortly.

Thank you and best,
Elise

**Comment by elisemercury** [comment]
Hi @yujinyuz,

After having done a bit more research, it turns out that it is not recommended to use pipx for libraries.

"If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead." See [here](https://linuxconfig.org/how-to-install-python-applications-in-isolated-environments-with-pipx).

Therefore this feature will not be implemented with difPy. Nonetheless, difPy v4 now comes with a .bat file included that you can use if you have a Windows machine and add it to your PATH system variables. This will allow you to use difPy everywhere on your machine just by entering `difPy` in the CLI. See more details [here](https://linuxconfig.org/how-to-install-python-applications-in-isolated-environments-with-pipx).

Thanks again for your suggestion!

All the best,
Elise
