### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by radry** [elisemercury/Duplicate-Image-Finder#80]
Aparently there is no memory limit built in and it will eat as much as it can get from windows.
"Preparing Files" completes fine but when searching the differences it eats a lot of memory.
My Windows is set up to automatically manage the pagefile and will happily enlarge it until the drive it's located on is full.
When that happens following error appears:

```
Traceback (most recent call last):
  File "G:\_DOWNLOADS\Duplicate-Image-Finder-4.0.1\difPy\dif.py", line 642, in <module>
    se = search(dif, similarity=args.similarity)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\_DOWNLOADS\Duplicate-Image-Finder-4.0.1\difPy\dif.py", line 242, in __init__
    self.result = self._main()
                  ^^^^^^^^^^^^
  File "G:\_DOWNLOADS\Duplicate-Image-Finder-4.0.1\difPy\dif.py", line 284, in _main
    items.append((id_a, id_b, self.__difpy_obj._tensor_dictionary[id_a], self.__difpy_obj._tensor_dictionary[id_b]))
MemoryError
```
The program will continue to run but stop without any further error after some minutes. There is no log file produced.

How to reproduce:
Run difPy in command line (similarity s=90) on a directory with ~60.000 images with 16GB ram and limited hard drive space for the pagefile.
Let windows manage the pagefile size.
Wait for "preparing files" to complete (will take an hour or so).

I don't know what would happen if the pagefile has a fixed size. I assume the same error will appear.

System:
Windows 10
16GB Ram
difPy 4.0.1

**Comment by breengles** [comment]
same here on Ubuntu, even with 64GB of ram

**Comment by breengles** [comment]
@KalyaSc I was not able to got it running with large image collection so I just switched to other tools for now. Hopefully, the solution will be found sooner

**Comment by elisemercury** [comment]
Hi all, 

difPy v4.1.0 now comes with improved handling of larger datasets, see the [guide](https://difpy.readthedocs.io/en/v4.1.0/faq.html#using-difpy-with-large-datasets). 

Additionally, the new version lets you adjust the number of [processes](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool) when Multiprocessing, so in order to reduce memory overhead, you can now manually lower this value. Previously, difPy was set to always use os.cpu_count(). For more details, I can recommend checking the [updated documentation of this feature](https://difpy.readthedocs.io/en/v4.1.0/usage.html#processes2). Nonetheless, keep in mind that lowering the number of simultaneous processes will also lead to a loss in performance, hence computation times will be longer. 

Let me know if this helps or if you're still encountering issues. 

Best,
Elise
