### ISSUE TITLE
A new process has started before the current process has finished its bootstrapping phase

### ISSUE THREAD

**Issue by pauljohn2000** [elisemercury/Duplicate-Image-Finder#85]
Ran a simple example using pif.py on a Mac (Intel) running Sonoma 14.1.1 and Python 3.11.1.

Code: 
  import difPy
  dif = difPy.build("/Users/paul/Pictures/New/")
  search = difPy.search(dif, in_folder=True)

Results:
The error repeated continually until I terminated the execution. See attached file for output.
[results.txt](https://github.com/elisemercury/Duplicate-Image-Finder/files/13527414/results.txt)

**Comment by pantegra** [comment]
I have the same issue running it on a Mac OS 14.1.2 m2 pro chip.  I get the same results when running it with python 3.11.x or 3.9.x, the Python version is not a factor. The result is the same.  Please fix this quickly. I have about 2k photos to try to clean out before I can post them.

**Comment by SurajBhari** [comment]
Any update about this. as i can see. its still happening.

**Comment by pauljohn2000** [comment]
I came back to looking at this issue and implemented the change that the Python runtime had suggested (duh!) and was successful.  So it would be helpful to add the implementation details in the difPy documentation.

Here's my code example (that worked):

`from multiprocessing import freeze_support
import difPy

if __name__ == '__main__':
    freeze_support()
    dif = difPy.build(['/SourceDir1/','/SourceDir2/'])
    search = difPy.search(dif)    
    for i in search.result:
        source = search.result[i]['location']
        for j in search.result[i]['matches']:
            print(source, 'matches', search.result[i]['matches'][j]['location'])

**Comment by elisemercury** [comment]
Hi all, 

difPy v4.1.0 now comes with improved handling of larger datasets, see the [guide](https://difpy.readthedocs.io/en/v4.1.0/faq.html#using-difpy-with-large-datasets). 

Additionally, the new version lets you adjust the number of [processes](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool) when Multiprocessing, so in order to reduce memory overhead, you can now manually lower this value. Previously, difPy was set to always use os.cpu_count(). For more details, I can recommend checking the [updated documentation of this feature](https://difpy.readthedocs.io/en/v4.1.0/faq.html#using-difpy-with-large-datasets). Nonetheless, keep in mind that lowering the number of simultaneous processes will also lead to a loss in performance, hence computation times will be longer. 

Let me know if this helps or if you're still encountering issues.

Best,
Elise

**Comment by n1lech** [comment]
> [difPy v4.1.0](https://github.com/elisemercury/Duplicate-Image-Finder/releases) has been released and I would recommend testing it to see if you can see some improvements.

I am running 4.1.0 on a mac m1 python3.11 and still have that issue.

However with the poc from @pauljohn2000 , it works.

```python3
import difPy
from multiprocessing import freeze_support

if __name__ == '__main__':
    freeze_support()
    dif = difPy.build('my/path')
    search = difPy.search(dif)
    print(search)
```

**Comment by Shnugs** [comment]
Running diffPy v4.1.0 on python3.12 and still have this issue. 

Just confirming that the POC that @pauljohn2000 posted works for py312.

**Comment by michaelcaterisano** [comment]
Same issue here. I didn't need everything in https://github.com/elisemercury/Duplicate-Image-Finder/issues/85#issuecomment-1927871788. The following works for me:

```
import difPy

if __name__ == "__main__":
    dif = difPy.build("./test")
    search = difPy.search(dif)
    print(search.result)
```

**Comment by elisemercury** [comment]
Hi all,

Sorry for the delay on this issue and thanks all for your contributions to this! 

I'm happy to let you know that difPy just got a new version update [v4.1.1](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.1.1) which incorporates `freeze_support()` by default before starting a difPy build or search process. Thanks for this suggestion @pauljohn2000 and thanks all for validating the fix.

This should hopefully provide a fix for the issue. Our tests have shown no issues - please let mw know if you do still encounter these from you end.

Best,
Elise
